name: Deploy Chart

on: workflow_dispatch

env:
  GKE_PROJECT: combocurve-exercise
  GKE_REGION: us-central1
  GKE_CLUSTER: combocurve
  NAMESPACE: hello-world
  RELEASE_NAME: hello-world
  CHART_NAME: combocurve/hello-world
  CHART_VERSION: 1.0.1
  
jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:

    - name: Checkout
      uses: actions/checkout@master

    - id: 'auth'
      uses: 'google-github-actions/auth@v1'
      with:
        credentials_json: '${{ secrets.GCP_CREDENTIALS }}'

    - name: 'Set up Cloud SDK'
      uses: 'google-github-actions/setup-gcloud@v1'

    - uses: azure/setup-kubectl@v3
      with:
        version: 'v1.27.1' # default is latest stable
      id: install-kubectl
      
    - uses: azure/setup-helm@v3
      with:
        version: 'v3.11.3' # default is latest (stable)
      id: install-helm

    - name: Configure auth
      run: |
        gcloud container clusters get-credentials $GKE_CLUSTER \
          --region $GKE_REGION \
          --project $GKE_PROJECT
        gcloud components install gke-gcloud-auth-plugin
        
    - name: Add Helm repository
      run: |
        helm repo add combocurve https://zjpiazza.github.io/combocurve-devops-exercise/
        
    - name: Deploy
      run: |
        helm -n $NAMESPACE upgrade $RELEASE_NAME $CHART_NAME --version $CHART_VERSION --wait
